name: Configure Git
description: Adds the necessary configurations to Git
inputs:
  tag-name:
    description: 'The name of the tag'
    required: false
    default: ${{ github.event.release.tag_name }}

runs:
  using: 'composite'
  steps:
    - name: Extract version from release tag
      shell: bash
      run: ./.github/scripts/extract-versions.sh "${{ inputs.tag-name }}"

    - name: Validate version
      shell: bash
      run: |
        if [[ ! $VERSION =~ ^[0-9]+\.[0-9]+\.[0-9]+$ ]]; then
          echo -e "\e[31mInvalid version format: $VERSION\e[0m"
          exit 1
        fi

    - name: Log version
      shell: bash
      run: |
        echo "\n"
        echo -e "\e[32mVERSION=$VERSION\e[0m"
        echo -e "\e[32mMINOR_VERSION=$MINOR_VERSION\e[0m"
        echo -e "\e[32mPATCH_VERSION=$PATCH_VERSION\e[0m"
        echo "\n"
        echo -e "\e[32mPATCH_BRANCH_NAME=$PATCH_BRANCH_NAME\e[0m"