name: Configure Git
description: Adds the necessary configurations to Git
inputs:
  tag-name:
    description: 'The name of the tag'
    required: false
    default: ${{ github.event.release.tag_name }}

runs:
  using: 'composite'
  steps:
    - name: Extract version from release tag
      shell: bash
      run: ./.github/scripts/extract-versions.sh "${{ inputs.tag-name }}"

    - name: Log version
      shell: bash
      run: |
        echo "VERSION=${{ github.env.VERSION }}"
        echo "MINOR_VERSION=${{ github.env.MINOR_VERSION }}"
        echo "PATCH_VERSION=${{ github.env.PATCH_VERSION }}"
        echo "PATCH_BRANCH_NAME=${{ github.env.PATCH_BRANCH_NAME }}"