name: Delete Release
description: Deletes release and its tag
inputs:
  github-token:
    description: 'The GitHub token'
    required: true
  release-id:
    description: 'The ID of the release to delete'
    required: false
    default: ${{ github.event.release.id }}
  release-tag:
    description: 'The tag of the release to delete'
    required: false
    default: ${{ github.event.release.tag_name }}
  repository:
    description: 'The repository to delete the release from'
    required: false
    default: ${{ github.repository }}

runs:
  using: 'composite'
  steps:
    - name: Delete release
      shell: bash
      run: |
        echo -e "\e[33mDeleting release due to failure in previous jobs\e[0m"
        echo "Deleting release due to failure in previous jobs"
        curl -X DELETE \
          -H "Authorization: token ${{ inputs.github-token }}" \
          https://api.github.com/repos/"${{ inputs.repository }}"/releases/"${{ inputs.release-id }}"

    - name: Delete release tag
      shell: bash
      run: |
        echo -e "\e[33mDeleting release tag due to failure in previous jobs\e[0m"
        curl -X DELETE \
          -H "Authorization: token ${{ inputs.github-token }}" \
          https://api.github.com/repos/"${{ inputs.repository }}"/git/refs/tags/"${{ inputs.release-tag }}"
