name: Extract Branch
description: Extracts the branch name from the tag
inputs:
  version:
    description: 'The version of the release'
    required: false
    default: "$VERSION"
  patch-branch-name:
    description: 'The patch branch name'
    required: false
    default: "$PATCH_BRANCH_NAME"

runs:
  using: 'composite'
  steps:
    - name: Extract branch name
      shell: bash
      run: |
        if [[ $1 =~ ^[0-9]+\.[0-9]+\.0$ ]]; then
            BRANCH_NAME=master
        else
            BRANCH_NAME=patch/$2
        fi
        echo "BRANCH_NAME=$BRANCH_NAME" >> "$GITHUB_ENV"

    - name: Log branch name
      shell: bash
      run: |
        echo "BRANCH_NAME=$BRANCH_NAME"