name: Extract Branch
description: Extracts the branch name from the tag
inputs:
  version:
    description: 'The version of the release'
    required: false
    default: ${{ github.env.VERSION }}

runs:
  using: 'composite'
  steps:
    - name: Extract branch name
      shell: bash
      run: ./.github/scripts/extract-branch.sh ${{ inputs.tag-name }}

    - name: Log branch name
      shell: bash
      run: |
        echo "BRANCH_NAME=${{ github.env.BRANCH_NAME }}"