name: Build and Test
description: Builds and tests the project
inputs:
  distribution:
    description: 'The distribution of Java to use'
    required: true
    default: 'corretto'
  java-version:
    description: 'The version of Java to use'
    required: true
    default: '17'
  architecture:
    description: 'The architecture of the Java version'
    required: true
    default: 'x64'
runs:
  using: 'composite'
  steps:
    - name: Checkout repository
      uses: actions/checkout@v4
      with:
        fetch-depth: 0

    - name: Setup Java
      uses: actions/setup-java@v2
      with:
        distribution: ${{ inputs.distribution }}
        java-version: ${{ inputs.java-version }}
        architecture: ${{ inputs.architecture }}

    - name: Cache Gradle packages
      uses: actions/cache@v2
      with:
        path: |
          ~/.gradle/caches
          ~/.gradle/wrapper
        key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*', '**/gradle-wrapper.properties') }}
        restore-keys: |
          ${{ runner.os }}-gradle


    - name: Build with Gradle
      shell: bash
      run: ./gradlew build

    - name: Test with Gradle
      shell: bash
      run: ./gradlew test

    - name: Cleanup Gradle Cache
      shell: bash
      run: |
        rm -f ~/.gradle/caches/modules-2/modules-2.lock
        rm -f ~/.gradle/caches/modules-2/gc.properties
