name: Update versions
description: Replaces %CURRENT_VERSION% string in every source file with the current version
inputs:
  version:
    description: 'The version of the release'
    required: false
    default: "VERSION"

runs:
  using: 'composite'
  steps:
    - name: Log every file
      shell: bash
      run: grep -rn %CURRENT_VERSION% ./src

    - name: Replace version
      shell: bash
      run: find /path/to/directory -type f -exec sed -i 's/%CURRENT_VERSION%/${{ inputs.version }}/g' {} +