name: Release Automation

on:
  release:
    types:
      - created

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

#      - name: Build
#        uses: ./.github/actions/execute-gradle
#        with:
#          gradle-commands: 'build'

  test:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - uses: actions/checkout@v4

#      - name: Test
#        uses: ./.github/actions/execute-gradle
#        with:
#          gradle-commands: 'test'

  publish-release:
    needs: test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Configure Git
        uses: ./.github/actions/configure-git
        with:
          user-name: ${{ secrets.USER_NAME }}
          user-mail: ${{ secrets.USER_MAIL }}

      - name: Extract versions
        uses: ./.github/actions/extract-version

      - name: Get branch
        uses: ./.github/actions/extract-branch

#      - name: Update versions
#        uses: ./.github/actions/update-versions
#        with:
#          user-token: ${{ secrets.USER_TOKEN }}

      - name: Create branches
        uses: ./.github/actions/create-branches
        with:
          user-token: ${{ secrets.USER_TOKEN }}

#      - name: Login to DockerHub
#        run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin
#
#      - name: Cache Docker layers
#        uses: actions/cache@v3
#        with:
#          path: /tmp/.buildx-cache
#          key: ${{ runner.os }}-buildx-${{ github.sha }}
#          restore-keys: |
#            ${{ runner.os }}-buildx-
#
#      - name: Build and push Docker image
#        run: |
#          docker build \
#            --tag ${{ secrets.DOCKER_USERNAME }}/${{ secrets.DOCKER_REPOSITORY }}:"$VERSION" \
#            -f Dockerfile .
#          docker push ${{ secrets.DOCKER_USERNAME }}/${{ secrets.DOCKER_REPOSITORY }}:"$VERSION"

  delete-release:
    needs:
      - build
      - test
      - publish-release
    if: ${{ failure() }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Delete release
        uses: ./.github/actions/delete-release
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
